# Generated by Django 3.2.3 on 2021-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='content',
        ),
        migrations.RemoveField(
            model_name='method',
            name='data_added',
        ),
        migrations.RemoveField(
            model_name='method',
            name='stars',
        ),
    ]
