# Generated by Django 3.2.3 on 2021-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20210602_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
