# Generated by Django 3.2.3 on 2021-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_alter_method_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
