# Generated by Django 3.2.3 on 2021-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_auto_20210702_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
