# Generated by Django 3.2.3 on 2021-07-02 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0007_alter_method_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='method',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='method',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
