# Generated by Django 3.2.3 on 2021-07-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0008_auto_20210702_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='method',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
